
# File di configurazione

[COMMON]
modello = ecita

# cartella_dataset = /run/media/daniele.carnevale/Daniele2TB/repo/estrazioni_puntuali/concatenazioni
cartella_dataset = /media/daniele/Daniele2TB/repo/estrazioni_puntuali/concatenazioni

# cartella_modelli_allenati = /run/media/daniele.carnevale/Daniele2TB/repo/QRF
cartella_modelli_allenati = /media/daniele/Daniele2TB/repo/QRF

# cartella_climatologie = /run/media/daniele.carnevale/Daniele2TB/repo/QRF/temperatura/climatologie
cartella_climatologie = /media/daniele/Daniele2TB/repo/QRF/temperatura/climatologie

# cartella_previsioni = /run/media/daniele.carnevale/Daniele2TB/repo/MeteoBricchi/dati1D
cartella_previsioni = /media/daniele/Daniele2TB/repo/MeteoBricchi/dati1D

soglia_evento = 20
quantili = [0.05, 0.25, 0.5, 0.75, 0.95]

fai_il_test = False
rifai_il_training = True
