
# File di configurazione

[COMMON]
modello = ecita

cartella_dataset = estrazioni_puntuali/concatenazioni
cartella_modelli_allenati = QRF
cartella_climatologie = temperatura/climatologie
cartella_previsioni = MeteoBricchi/dati1D

soglia_evento = 35
quantili = [0.05, 0.25, 0.5, 0.75, 0.95]

fai_il_test = False
rifai_il_training = True
